<a href="https://colab.research.google.com/github/angelaaaateng/ML_COVID_PREDICTION/blob/master/Exploration_COVID19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Libraries + Load Data

In [37]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# amber additions
!pwd

/Users/angelateng/NYU_GoogleDrive/GitHub/ML_COVID_PREDICTION

### DSP Data (Key = PHCaseNo)

In [3]:
data = pd.read_csv('openrefine_PHCASES_COVID_04162020_PHnum.csv')
data.head()

,Case No.,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,Date of Final Status (recovered/expired),Final Diagnosis,Age Group,Location,Location 1,Location 2,Latitude,Longitude,Residence Lat,Residence Long
0,PH00001,F,38,chinese,None,Yes (China); Wife of PH02,china,NaN,NaN,NaN,...,Sun Mar 15 00:00:00 EDT 2020,NaN,31 - 40,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909
1,PH00002,M,44,chinese,None,Yes (China); Husband of PH1,china,NaN,NaN,NaN,...,Sat Feb 01 00:00:00 EST 2020,severe pneumonia,41 - 50,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909
2,PH00003,F,60,chinese,None,Yes (China),china,NaN,NaN,NaN,...,Sun Mar 15 00:00:00 EDT 2020,NaN,51 - 60,Manila City,Manila City,NaN,14.615867,120.980991,14.598727,120.9819909
3,PH00004,M,48,filipino,Taguig City,Yes (Japan),japan,NaN,NaN,NaN,...,Thu Mar 19 00:00:00 EDT 2020,"asymptomatic, negative test result",41 - 50,Taguig City,Taguig City,NaN,14.606904,121.020392,14.517274,121.0496133
4,PH00005,M,62,filipino,"Cainta, Rizal",Husband of PH06,none,NaN,NaN,NaN,...,Thu Mar 12 00:00:00 EDT 2020,"acute respiratory distress syndrome, severe pn...",61 - 70,"Cainta, Rizal",Cainta,Rizal,14.409635,121.037425,14.586506,121.1138255

In [4]:
data.columns

Index(['Case No.', 'Sex', 'Age', 'Nationality', 'Residence in the Philippines',
       'History of Travel / Exposure', 'Travel History 1', 'Travel History 2',
       'Travel History 3', 'Travel History 4', 'Epi_Link',
       'Date of Onset of Symptoms', 'Date of Admission',
       'Date of Lab Confirmation', 'Date of Announcement to the Public',
       'Admission / Consultation', 'Symptoms', 'Other disease', 'Status',
       'Health Status', 'Date of Final Status (recovered/expired)',
       'Final Diagnosis', 'Age Group', 'Location', 'Location 1', 'Location 2',
       'Latitude', 'Longitude', 'Residence Lat', 'Residence Long'],
      dtype='object')

In [5]:
data = data.rename(columns={'Case No.': 'phcaseno'})

In [6]:
# data = data.rename(columns={'Location 1': 'case_location'})

In [7]:
data.dtypes

phcaseno                                     object
Sex                                          object
Age                                           int64
Nationality                                  object
Residence in the Philippines                 object
History of Travel / Exposure                 object
Travel History 1                             object
Travel History 2                             object
Travel History 3                             object
Travel History 4                             object
Epi_Link                                     object
Date of Onset of Symptoms                    object
Date of Admission                            object
Date of Lab Confirmation                     object
Date of Announcement to the Public           object
Admission / Consultation                     object
Symptoms                                     object
Other disease                                object
Status                                       object
Health Status                                object
Date of Final Status (recovered/expired)     object
Final Diagnosis                              object
Age Group                                    object
Location                                     object
Location 1                                   object
Location 2                                   object
Latitude                                    float64
Longitude                                   float64
Residence Lat                               float64
Residence Long                               object
dtype: object

In [8]:
data.shape

(3246, 30)

### Department of Health Data (Key = CaseCode)

In [32]:
# # Incorrect, don't run
# doh = pd.read_csv('opnrefine_DOH_data.csv')
# doh.head()

,CaseCode,Age,AgeGroup,Sex,DateRepConf,DateRecover,DateDied,RemovalType,DateRepRem,Admitted,...,Residence Lat,Residence Long,Column,Column2,Column3,Column4,Column5,Column6,Column7,Column8
0,C100119,30,30 to 34,Male,Sun Apr 12 00:00:00 EDT 2020,NaN,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C100264,57,55 to 59,Male,Sun Mar 29 00:00:00 EDT 2020,NaN,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C100660,42,40 to 44,Female,Thu Apr 02 00:00:00 EDT 2020,NaN,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C100776,42,40 to 44,Male,Wed Apr 01 00:00:00 EDT 2020,NaN,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C101015,79,75 to 79,Male,Fri Apr 03 00:00:00 EDT 2020,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
# doh.columns

Index(['CaseCode', 'Age', 'AgeGroup', 'Sex', 'DateRepConf', 'DateRecover',
       'DateDied', 'RemovalType', 'DateRepRem', 'Admitted', 'RegionRes',
       'ProvCityRes', 'Location', 'case_location', 'Location 2', 'Latitude',
       'Longitude', 'Case No.', 'Nationality', 'Residence in the Philippines',
       'History of Travel / Exposure', 'Travel History', 'Epi_Link',
       'Date of Onset of Symptoms', 'Date of Admission',
       'Date of Lab Confirmation', 'Date of Announcement to the Public',
       'Admission / Consultation', 'Symptoms', 'Other disease', 'Status',
       'Health Status', 'Date of Final Status (recovered/expired)',
       'Final Diagnosis', 'Age Group', 'Residence Lat', 'Residence Long',
       'Column', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8'],
      dtype='object')

In [61]:
# doh = doh.rename(columns={'Location 1': 'case_location'})

In [62]:
# doh.shape

(8469, 45)

## Diagnosis Descriptions and Variables

In [9]:
data.groupby('Health Status').size()

Health Status
asymptomatic        38
critical             3
died               108
for validation    2983
mild                57
recovered           51
severe               6
dtype: int64

In [39]:
# doh.groupby('Health Status').size()

Health Status
Asymptomatic        38
Critical             3
Died               108
For validation    2983
Mild                57
Recovered           51
Severe               6
dtype: int64

## Feature Engineering: Location

In [67]:
# location_df = doh[['case_location', 'RegionRes',
#  'ProvCityRes',
#  'Location',
#  'Location 2',
#  'Latitude',
#  'Longitude']]

In [68]:
# location_df

,case_location,RegionRes,ProvCityRes,Location,Location 2,Latitude,Longitude
0,ParaÃ±aque City,Metro Manila,City of ParaÃ±aque,"ParaÃ±aque City, Metro Manila",Metro Manila,14.479310,121.019200
1,Mandaluyong City,Metro Manila,City of Mandaluyong,Mandaluyong City,NaN,14.579530,121.035000
2,Pasig City,Metro Manila,City of Pasig,"Pasig City, Metro Manila",Metro Manila,14.576160,121.084600
3,Pila,Laguna,Pila,"Pila, Laguna",Laguna,14.234500,121.365000
4,Unisan,Quezon,Unisan,"Unisan, Quezon",Quezon,13.860430,122.014200
...,...,...,...,...,...,...,...
8464,For validation,NaN,NaN,For validation,NaN,14.615867,120.980991
8465,For validation,NaN,NaN,For validation,NaN,14.615867,120.980991
8466,For validation,NaN,NaN,For validation,NaN,14.615867,120.980991
8467,For validation,NaN,NaN,For validation,NaN,14.615867,120.980991
8468,For validation,NaN,NaN,For validation,NaN,14.615867,120.980991

In [69]:
# master = pd.merge(data, location_df, how='left', on= 'case_location')

In [70]:
# master.head()

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,Column5,Column6,Column7,Column8,RegionRes,ProvCityRes,Location_y,Location 2_y,Latitude_y,Longitude_y
0,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
1,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
2,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
3,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
4,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982

In [71]:
# master_cols = master.columns.tolist()
# master_cols

['phcaseno',
 'Sex',
 'Age',
 'Nationality',
 'Residence in the Philippines',
 'History of Travel / Exposure',
 'Travel History 1',
 'Travel History 2',
 'Travel History 3',
 'Travel History 4',
 'Epi_Link',
 'Date of Onset of Symptoms',
 'Date of Admission',
 'Date of Lab Confirmation',
 'Date of Announcement to the Public',
 'Admission / Consultation',
 'Symptoms',
 'Symptoms 1',
 'Symptoms 2',
 'Symptoms 3',
 'Other disease',
 'Other disease 1',
 'Other disease 2',
 'Other disease 3',
 'Other disease 4',
 'Other disease 5',
 'Status',
 'Health Status',
 'Date of Final Status (recovered/expired)',
 'Final Diagnosis',
 'Age Group',
 'Location_x',
 'case_location',
 'Location 2_x',
 'Latitude_x',
 'Longitude_x',
 'Residence Lat',
 'Residence Long',
 'Column',
 'Column2',
 'Column3',
 'Column4',
 'Column5',
 'Column6',
 'Column7',
 'Column8',
 'RegionRes',
 'ProvCityRes',
 'Location_y',
 'Location 2_y',
 'Latitude_y',
 'Longitude_y']

In [72]:
# col_drop_list = ['Column',
#  'Column2',
#  'Column3',
#  'Column4',
#  'Column5',
#  'Column6',
#  'Column7',
#  'Column8',]

In [73]:
# master = master.drop(col_drop_list, axis = 1) 
# master.head()

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,Latitude_x,Longitude_x,Residence Lat,Residence Long,RegionRes,ProvCityRes,Location_y,Location 2_y,Latitude_y,Longitude_y
0,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,14.61348,120.98095,14.598727,120.9819909,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
1,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,14.61348,120.98095,14.598727,120.9819909,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
2,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,14.61348,120.98095,14.598727,120.9819909,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
3,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,14.61348,120.98095,14.598727,120.9819909,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982
4,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,14.61348,120.98095,14.598727,120.9819909,Metro Manila,City of Manila,"Manila City, Metro Manila",Metro Manila,14.59873,120.982

In [75]:
# master['case_location']

0             Manila City
1             Manila City
2             Manila City
3             Manila City
4             Manila City
                ...
2112834    For validation
2112835    For validation
2112836    For validation
2112837    For validation
2112838    For validation
Name: case_location, Length: 2112839, dtype: object

In [80]:
# master.shape

(2112839, 44)

In [79]:
# data.shape

(3246, 46)

In [83]:
# master = data.merge(location_df, on='case_location', how='inner', indicator=True)

In [84]:
# master.shape

(2112833, 53)

In [ ]:
# not working, so we'll try geo encoding instead

In [10]:
data.head()

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,Date of Final Status (recovered/expired),Final Diagnosis,Age Group,Location,Location 1,Location 2,Latitude,Longitude,Residence Lat,Residence Long
0,PH00001,F,38,chinese,None,Yes (China); Wife of PH02,china,NaN,NaN,NaN,...,Sun Mar 15 00:00:00 EDT 2020,NaN,31 - 40,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909
1,PH00002,M,44,chinese,None,Yes (China); Husband of PH1,china,NaN,NaN,NaN,...,Sat Feb 01 00:00:00 EST 2020,severe pneumonia,41 - 50,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909
2,PH00003,F,60,chinese,None,Yes (China),china,NaN,NaN,NaN,...,Sun Mar 15 00:00:00 EDT 2020,NaN,51 - 60,Manila City,Manila City,NaN,14.615867,120.980991,14.598727,120.9819909
3,PH00004,M,48,filipino,Taguig City,Yes (Japan),japan,NaN,NaN,NaN,...,Thu Mar 19 00:00:00 EDT 2020,"asymptomatic, negative test result",41 - 50,Taguig City,Taguig City,NaN,14.606904,121.020392,14.517274,121.0496133
4,PH00005,M,62,filipino,"Cainta, Rizal",Husband of PH06,none,NaN,NaN,NaN,...,Thu Mar 12 00:00:00 EDT 2020,"acute respiratory distress syndrome, severe pn...",61 - 70,"Cainta, Rizal",Cainta,Rizal,14.409635,121.037425,14.586506,121.1138255

In [12]:
data_clean = data.drop(['Travel History 1',
 'Travel History 2',
 'Travel History 3',
 'Travel History 4'], axis = 1) 
data_clean.head()

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Epi_Link,Date of Onset of Symptoms,Date of Admission,Date of Lab Confirmation,...,Date of Final Status (recovered/expired),Final Diagnosis,Age Group,Location,Location 1,Location 2,Latitude,Longitude,Residence Lat,Residence Long
0,PH00001,F,38,chinese,None,Yes (China); Wife of PH02,Wife of PH2,Tue Jan 21 00:00:00 EST 2020,Sat Jan 25 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,Sun Mar 15 00:00:00 EDT 2020,NaN,31 - 40,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909
1,PH00002,M,44,chinese,None,Yes (China); Husband of PH1,Husband of PH1,Sat Jan 18 00:00:00 EST 2020,Sat Jan 25 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,Sat Feb 01 00:00:00 EST 2020,severe pneumonia,41 - 50,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909
2,PH00003,F,60,chinese,None,Yes (China),Traveled to Cebu and Bohol. Was already in Chi...,Tue Jan 21 00:00:00 EST 2020,Wed Jan 22 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,Sun Mar 15 00:00:00 EDT 2020,NaN,51 - 60,Manila City,Manila City,NaN,14.615867,120.980991,14.598727,120.9819909
3,PH00004,M,48,filipino,Taguig City,Yes (Japan),NaN,Tue Mar 03 00:00:00 EST 2020,Fri Mar 06 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,...,Thu Mar 19 00:00:00 EDT 2020,"asymptomatic, negative test result",41 - 50,Taguig City,Taguig City,NaN,14.606904,121.020392,14.517274,121.0496133
4,PH00005,M,62,filipino,"Cainta, Rizal",Husband of PH06,Husband of PH6,Tue Feb 25 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,...,Thu Mar 12 00:00:00 EDT 2020,"acute respiratory distress syndrome, severe pn...",61 - 70,"Cainta, Rizal",Cainta,Rizal,14.409635,121.037425,14.586506,121.1138255

In [28]:
data_clean['phcaseno'].values.tolist()

['PH00001',
 'PH00002',
 'PH00003',
 'PH00004',
 'PH00005',
 'PH00006',
 'PH00007',
 'PH00008',
 'PH00009',
 'PH00010',
 'PH00011',
 'PH00012',
 'PH00013',
 'PH00014',
 'PH00015',
 'PH00016',
 'PH00017',
 'PH00018',
 'PH00019',
 'PH00020',
 'PH00021',
 'PH00022',
 'PH00023',
 'PH00024',
 'PH00025',
 'PH00026',
 'PH00027',
 'PH00028',
 'PH00029',
 'PH00030',
 'PH00031',
 'PH00032',
 'PH00033',
 'PH00034',
 'PH00035',
 'PH00036',
 'PH00037',
 'PH00038',
 'PH00039',
 'PH00040',
 'PH00041',
 'PH00042',
 'PH00043',
 'PH00044',
 'PH00045',
 'PH00046',
 'PH00047',
 'PH00048',
 'PH00049',
 'PH00050',
 'PH00051',
 'PH00052',
 'PH00053',
 'PH00054',
 'PH00055',
 'PH00056',
 'PH00057',
 'PH00058',
 'PH00059',
 'PH00060',
 'PH00061',
 'PH00062',
 'PH00063',
 'PH00064',
 'PH00065',
 'PH00066',
 'PH00067',
 'PH00068',
 'PH00069',
 'PH00070',
 'PH00071',
 'PH00072',
 'PH00073',
 'PH00074',
 'PH00075',
 'PH00076',
 'PH00077',
 'PH00078',
 'PH00079',
 'PH00080',
 'PH00081',
 'PH00082',
 'PH00083',
 'PH00084',
 'PH00085',
 'PH00086',
 'PH00087',
 'PH00088',
 'PH00089',
 'PH00090',
 'PH00091',
 'PH00092',
 'PH00093',
 'PH00094',
 'PH00095',
 'PH00096',
 'PH00097',
 'PH00098',
 'PH00099',
 'PH00100',
 'PH00101',
 'PH00102',
 'PH00103',
 'PH00104',
 'PH00105',
 'PH00106',
 'PH00107',
 'PH00108',
 'PH00109',
 'PH00110',
 'PH00111',
 'PH00112',
 'PH00113',
 'PH00114',
 'PH00115',
 'PH00116',
 'PH00117',
 'PH00118',
 'PH00119',
 'PH00120',
 'PH00121',
 'PH00122',
 'PH00123',
 'PH00124',
 'PH00125',
 'PH00126',
 'PH00127',
 'PH00128',
 'PH00129',
 'PH00130',
 'PH00131',
 'PH00132',
 'PH00133',
 'PH00134',
 'PH00135',
 'PH00136',
 'PH00137',
 'PH00138',
 'PH00139',
 'PH00140',
 'PH00141',
 'PH00142',
 'PH00143',
 'PH00144',
 'PH00145',
 'PH00146',
 'PH00147',
 'PH00148',
 'PH00149',
 'PH00150',
 'PH00151',
 'PH00152',
 'PH00153',
 'PH00154',
 'PH00155',
 'PH00156',
 'PH00157',
 'PH00158',
 'PH00159',
 'PH00160',
 'PH00161',
 'PH00162',
 'PH00163',
 'PH00164',
 'PH00165',
 'PH00166',
 'PH00167',
 'PH00168',
 'PH00169',
 'PH00170',
 'PH00171',
 'PH00172',
 'PH00173',
 'PH00174',
 'PH00175',
 'PH00176',
 'PH00177',
 'PH00178',
 'PH00179',
 'PH00180',
 'PH00181',
 'PH00182',
 'PH00183',
 'PH00184',
 'PH00185',
 'PH00186',
 'PH00187',
 'PH00188',
 'PH00189',
 'PH00190',
 'PH00191',
 'PH00192',
 'PH00193',
 'PH00194',
 'PH00195',
 'PH00196',
 'PH00197',
 'PH00198',
 'PH00199',
 'PH00200',
 'PH00201',
 'PH00202',
 'PH00203',
 'PH00204',
 'PH00205',
 'PH00206',
 'PH00207',
 'PH00208',
 'PH00209',
 'PH00210',
 'PH00211',
 'PH00212',
 'PH00213',
 'PH00214',
 'PH00215',
 'PH00216',
 'PH00217',
 'PH00218',
 'PH00219',
 'PH00220',
 'PH00221',
 'PH00222',
 'PH00223',
 'PH00224',
 'PH00225',
 'PH00226',
 'PH00227',
 'PH00228',
 'PH00229',
 'PH00230',
 'PH00231',
 'PH00232',
 'PH00233',
 'PH00234',
 'PH00235',
 'PH00236',
 'PH00237',
 'PH00238',
 'PH00239',
 'PH00240',
 'PH00241',
 'PH00242',
 'PH00243',
 'PH00244',
 'PH00245',
 'PH00246',
 'PH00247',
 'PH00248',
 'PH00249',
 'PH00250',
 'PH00251',
 'PH00252',
 'PH00253',
 'PH00254',
 'PH00255',
 'PH00256',
 'PH00257',
 'PH00258',
 'PH00259',
 'PH00260',
 'PH00261',
 'PH00262',
 'PH00263',
 'PH00264',
 'PH00265',
 'PH00266',
 'PH00267',
 'PH00268',
 'PH00269',
 'PH00270',
 'PH00271',
 'PH00272',
 'PH00273',
 'PH00274',
 'PH00275',
 'PH00276',
 'PH00277',
 'PH00278',
 'PH00279',
 'PH00280',
 'PH00281',
 'PH00282',
 'PH00283',
 'PH00284',
 'PH00285',
 'PH00286',
 'PH00287',
 'PH00288',
 'PH00289',
 'PH00290',
 'PH00291',
 'PH00292',
 'PH00293',
 'PH00294',
 'PH00295',
 'PH00296',
 'PH00297',
 'PH00298',
 'PH00299',
 'PH00300',
 'PH00301',
 'PH00302',
 'PH00303',
 'PH00304',
 'PH00305',
 'PH00306',
 'PH00307',
 'PH00308',
 'PH00309',
 'PH00310',
 'PH00311',
 'PH00312',
 'PH00313',
 'PH00314',
 'PH00315',
 'PH00316',
 'PH00317',
 'PH00318',
 'PH00319',
 'PH00320',
 'PH00321',
 'PH00322',
 'PH00323',
 'PH00324',
 'PH00325',
 'PH00326',
 'PH00327',
 'PH00328',
 'PH00329',
 'PH00330',
 'PH00331',
 'PH00332',
 'PH00333',
 'PH00334',
 'PH00335',
 'PH00336',
 'PH00337',
 'PH00338',
 'PH00339',
 'PH00340',
 'PH00341',
 'PH00342',
 'PH00343',
 'PH00344',
 'PH00345',
 'PH00346',
 'PH00347',
 'PH00348',
 'PH00349',
 'PH00350',
 'PH00351',
 'PH00352',
 'PH00353',
 'PH00354',
 'PH00355',
 'PH00356',
 'PH00357',
 'PH00358',
 'PH00359',
 'PH00360',
 'PH00361',
 'PH00362',
 'PH00363',
 'PH00364',
 'PH00365',
 'PH00366',
 'PH00367',
 'PH00368',
 'PH00369',
 'PH00370',
 'PH00371',
 'PH00372',
 'PH00373',
 'PH00374',
 'PH00375',
 'PH00376',
 'PH00377',
 'PH00378',
 'PH00379',
 'PH00380',
 'PH00381',
 'PH00382',
 'PH00383',
 'PH00384',
 'PH00385',
 'PH00386',
 'PH00387',
 'PH00388',
 'PH00389',
 'PH00390',
 'PH00391',
 'PH00392',
 'PH00393',
 'PH00394',
 'PH00395',
 'PH00396',
 'PH00397',
 'PH00398',
 'PH00399',
 'PH00400',
 'PH00401',
 'PH00402',
 'PH00403',
 'PH00404',
 'PH00405',
 'PH00406',
 'PH00407',
 'PH00408',
 'PH00409',
 'PH00410',
 'PH00411',
 'PH00412',
 'PH00413',
 'PH00414',
 'PH00415',
 'PH00416',
 'PH00417',
 'PH00418',
 'PH00419',
 'PH00420',
 'PH00421',
 'PH00422',
 'PH00423',
 'PH00424',
 'PH00425',
 'PH00426',
 'PH00427',
 'PH00428',
 'PH00429',
 'PH00430',
 'PH00431',
 'PH00432',
 'PH00433',
 'PH00434',
 'PH00435',
 'PH00436',
 'PH00437',
 'PH00438',
 'PH00439',
 'PH00440',
 'PH00441',
 'PH00442',
 'PH00443',
 'PH00444',
 'PH00445',
 'PH00446',
 'PH00447',
 'PH00448',
 'PH00449',
 'PH00450',
 'PH00451',
 'PH00452',
 'PH00453',
 'PH00454',
 'PH00455',
 'PH00456',
 'PH00457',
 'PH00458',
 'PH00459',
 'PH00460',
 'PH00461',
 'PH00462',
 'PH00463',
 'PH00464',
 'PH00465',
 'PH00466',
 'PH00467',
 'PH00468',
 'PH00469',
 'PH00470',
 'PH00471',
 'PH00472',
 'PH00473',
 'PH00474',
 'PH00475',
 'PH00476',
 'PH00477',
 'PH00478',
 'PH00479',
 'PH00480',
 'PH00481',
 'PH00482',
 'PH00483',
 'PH00484',
 'PH00485',
 'PH00486',
 'PH00487',
 'PH00488',
 'PH00489',
 'PH00490',
 'PH00491',
 'PH00492',
 'PH00493',
 'PH00494',
 'PH00495',
 'PH00496',
 'PH00497',
 'PH00498',
 'PH00499',
 'PH00500',
 'PH00501',
 'PH00502',
 'PH00503',
 'PH00504',
 'PH00505',
 'PH00506',
 'PH00507',
 'PH00508',
 'PH00509',
 'PH00510',
 'PH00511',
 'PH00512',
 'PH00513',
 'PH00514',
 'PH00515',
 'PH00516',
 'PH00517',
 'PH00518',
 'PH00519',
 'PH00520',
 'PH00521',
 'PH00522',
 'PH00523',
 'PH00524',
 'PH00525',
 'PH00526',
 'PH00527',
 'PH00528',
 'PH00529',
 'PH00530',
 'PH00531',
 'PH00532',
 'PH00533',
 'PH00534',
 'PH00535',
 'PH00536',
 'PH00537',
 'PH00538',
 'PH00539',
 'PH00540',
 'PH00541',
 'PH00542',
 'PH00543',
 'PH00544',
 'PH00545',
 'PH00546',
 'PH00547',
 'PH00548',
 'PH00549',
 'PH00550',
 'PH00551',
 'PH00552',
 'PH00553',
 'PH00554',
 'PH00555',
 'PH00556',
 'PH00557',
 'PH00558',
 'PH00559',
 'PH00560',
 'PH00561',
 'PH00562',
 'PH00563',
 'PH00564',
 'PH00565',
 'PH00566',
 'PH00567',
 'PH00568',
 'PH00569',
 'PH00570',
 'PH00571',
 'PH00572',
 'PH00573',
 'PH00574',
 'PH00575',
 'PH00576',
 'PH00577',
 'PH00578',
 'PH00579',
 'PH00580',
 'PH00581',
 'PH00582',
 'PH00583',
 'PH00584',
 'PH00585',
 'PH00586',
 'PH00587',
 'PH00588',
 'PH00589',
 'PH00590',
 'PH00591',
 'PH00592',
 'PH00593',
 'PH00594',
 'PH00595',
 'PH00596',
 'PH00597',
 'PH00598',
 'PH00599',
 'PH00600',
 'PH00601',
 'PH00602',
 'PH00603',
 'PH00604',
 'PH00605',
 'PH00606',
 'PH00607',
 'PH00608',
 'PH00609',
 'PH00610',
 'PH00611',
 'PH00612',
 'PH00613',
 'PH00614',
 'PH00615',
 'PH00616',
 'PH00617',
 'PH00618',
 'PH00619',
 'PH00620',
 'PH00621',
 'PH00622',
 'PH00623',
 'PH00624',
 'PH00625',
 'PH00626',
 'PH00627',
 'PH00628',
 'PH00629',
 'PH00630',
 'PH00631',
 'PH00632',
 'PH00633',
 'PH00634',
 'PH00635',
 'PH00636',
 'PH00637',
 'PH00638',
 'PH00639',
 'PH00640',
 'PH00641',
 'PH00642',
 'PH00643',
 'PH00644',
 'PH00645',
 'PH00646',
 'PH00647',
 'PH00648',
 'PH00649',
 'PH00650',
 'PH00651',
 'PH00652',
 'PH00653',
 'PH00654',
 'PH00655',
 'PH00656',
 'PH00657',
 'PH00658',
 'PH00659',
 'PH00660',
 'PH00661',
 'PH00662',
 'PH00663',
 'PH00664',
 'PH00665',
 'PH00666',
 'PH00667',
 'PH00668',
 'PH00669',
 'PH00670',
 'PH00671',
 'PH00672',
 'PH00673',
 'PH00674',
 'PH00675',
 'PH00676',
 'PH00677',
 'PH00678',
 'PH00679',
 'PH00680',
 'PH00681',
 'PH00682',
 'PH00683',
 'PH00684',
 'PH00685',
 'PH00686',
 'PH00687',
 'PH00688',
 'PH00689',
 'PH00690',
 'PH00691',
 'PH00692',
 'PH00693',
 'PH00694',
 'PH00695',
 'PH00696',
 'PH00697',
 'PH00698',
 'PH00699',
 'PH00700',
 'PH00701',
 'PH00702',
 'PH00703',
 'PH00704',
 'PH00705',
 'PH00706',
 'PH00707',
 'PH00708',
 'PH00709',
 'PH00710',
 'PH00711',
 'PH00712',
 'PH00713',
 'PH00714',
 'PH00715',
 'PH00716',
 'PH00717',
 'PH00718',
 'PH00719',
 'PH00720',
 'PH00721',
 'PH00722',
 'PH00723',
 'PH00724',
 'PH00725',
 'PH00726',
 'PH00727',
 'PH00728',
 'PH00729',
 'PH00730',
 'PH00731',
 'PH00732',
 'PH00733',
 'PH00734',
 'PH00735',
 'PH00736',
 'PH00737',
 'PH00738',
 'PH00739',
 'PH00740',
 'PH00741',
 'PH00742',
 'PH00743',
 'PH00744',
 'PH00745',
 'PH00746',
 'PH00747',
 'PH00748',
 'PH00749',
 'PH00750',
 'PH00751',
 'PH00752',
 'PH00753',
 'PH00754',
 'PH00755',
 'PH00756',
 'PH00757',
 'PH00758',
 'PH00759',
 'PH00760',
 'PH00761',
 'PH00762',
 'PH00763',
 'PH00764',
 'PH00765',
 'PH00766',
 'PH00767',
 'PH00768',
 'PH00769',
 'PH00770',
 'PH00771',
 'PH00772',
 'PH00773',
 'PH00774',
 'PH00775',
 'PH00776',
 'PH00777',
 'PH00778',
 'PH00779',
 'PH00780',
 'PH00781',
 'PH00782',
 'PH00783',
 'PH00784',
 'PH00785',
 'PH00786',
 'PH00787',
 'PH00788',
 'PH00789',
 'PH00790',
 'PH00791',
 'PH00792',
 'PH00793',
 'PH00794',
 'PH00795',
 'PH00796',
 'PH00797',
 'PH00798',
 'PH00799',
 'PH00800',
 'PH00801',
 'PH00802',
 'PH00803',
 'PH00804',
 'PH00805',
 'PH00806',
 'PH00807',
 'PH00808',
 'PH00809',
 'PH00810',
 'PH00811',
 'PH00812',
 'PH00813',
 'PH00814',
 'PH00815',
 'PH00816',
 'PH00817',
 'PH00818',
 'PH00819',
 'PH00820',
 'PH00821',
 'PH00822',
 'PH00823',
 'PH00824',
 'PH00825',
 'PH00826',
 'PH00827',
 'PH00828',
 'PH00829',
 'PH00830',
 'PH00831',
 'PH00832',
 'PH00833',
 'PH00834',
 'PH00835',
 'PH00836',
 'PH00837',
 'PH00838',
 'PH00839',
 'PH00840',
 'PH00841',
 'PH00842',
 'PH00843',
 'PH00844',
 'PH00845',
 'PH00846',
 'PH00847',
 'PH00848',
 'PH00849',
 'PH00850',
 'PH00851',
 'PH00852',
 'PH00853',
 'PH00854',
 'PH00855',
 'PH00856',
 'PH00857',
 'PH00858',
 'PH00859',
 'PH00860',
 'PH00861',
 'PH00862',
 'PH00863',
 'PH00864',
 'PH00865',
 'PH00866',
 'PH00867',
 'PH00868',
 'PH00869',
 'PH00870',
 'PH00871',
 'PH00872',
 'PH00873',
 'PH00874',
 'PH00875',
 'PH00876',
 'PH00877',
 'PH00878',
 'PH00879',
 'PH00880',
 'PH00881',
 'PH00882',
 'PH00883',
 'PH00884',
 'PH00885',
 'PH00886',
 'PH00887',
 'PH00888',
 'PH00889',
 'PH00890',
 'PH00891',
 'PH00892',
 'PH00893',
 'PH00894',
 'PH00895',
 'PH00896',
 'PH00897',
 'PH00898',
 'PH00899',
 'PH00900',
 'PH00901',
 'PH00902',
 'PH00903',
 'PH00904',
 'PH00905',
 'PH00906',
 'PH00907',
 'PH00908',
 'PH00909',
 'PH00910',
 'PH00911',
 'PH00912',
 'PH00913',
 'PH00914',
 'PH00915',
 'PH00916',
 'PH00917',
 'PH00918',
 'PH00919',
 'PH00920',
 'PH00921',
 'PH00922',
 'PH00923',
 'PH00924',
 'PH00925',
 'PH00926',
 'PH00927',
 'PH00928',
 'PH00929',
 'PH00930',
 'PH00931',
 'PH00932',
 'PH00933',
 'PH00934',
 'PH00935',
 'PH00936',
 'PH00937',
 'PH00938',
 'PH00939',
 'PH00940',
 'PH00941',
 'PH00942',
 'PH00943',
 'PH00944',
 'PH00945',
 'PH00946',
 'PH00947',
 'PH00948',
 'PH00949',
 'PH00950',
 'PH00951',
 'PH00952',
 'PH00953',
 'PH00954',
 'PH00955',
 'PH00956',
 'PH00957',
 'PH00958',
 'PH00959',
 'PH00960',
 'PH00961',
 'PH00962',
 'PH00963',
 'PH00964',
 'PH00965',
 'PH00966',
 'PH00967',
 'PH00968',
 'PH00969',
 'PH00970',
 'PH00971',
 'PH00972',
 'PH00973',
 'PH00974',
 'PH00975',
 'PH00976',
 'PH00977',
 'PH00978',
 'PH00979',
 'PH00980',
 'PH00981',
 'PH00982',
 'PH00983',
 'PH00984',
 'PH00985',
 'PH00986',
 'PH00987',
 'PH00988',
 'PH00989',
 'PH00990',
 'PH00991',
 'PH00992',
 'PH00993',
 'PH00994',
 'PH00995',
 'PH00996',
 'PH00997',
 'PH00998',
 'PH00999',
 'PH01000',
 ...]

In [15]:
data_clean.to_csv('/Users/angelateng/NYU_GoogleDrive/GitHub/ML_COVID_PREDICTION/data_clean.csv', index= False, header=True)

In [162]:
# # ! pip install geopy
# # conda install -c conda-forge geopy 
# # ! pip install --user ipykernel
# # ! python -m ipykernel install --user --name=venv

# # Install a conda package in the current Jupyter kernel
# # import sys
# # !conda install --yes --prefix {sys.prefix} reverse_geocoder

# # Install a pip package in the current Jupyter kernel
# import sys
# !{sys.executable} -m pip install reverse_geocoder

In [16]:
# # Install a pip package in the current Jupyter kernel
# import sys
# !{sys.executable} -m pip install geopy

One Hot Encoding Symptoms

In [21]:
data_clean.columns

Index(['phcaseno', 'Sex', 'Age', 'Nationality', 'Residence in the Philippines',
       'History of Travel / Exposure', 'Epi_Link', 'Date of Onset of Symptoms',
       'Date of Admission', 'Date of Lab Confirmation',
       'Date of Announcement to the Public', 'Admission / Consultation',
       'Symptoms', 'Other disease', 'Status', 'Health Status',
       'Date of Final Status (recovered/expired)', 'Final Diagnosis',
       'Age Group', 'Location', 'Location 1', 'Location 2', 'Latitude',
       'Longitude', 'Residence Lat', 'Residence Long'],
      dtype='object')

In [23]:
symptoms = data_clean.set_index('phcaseno').Symptoms.str.split(',', expand=True).stack()

In [24]:
symptoms

phcaseno
PH00002   0                       fever
          1                       cough
          2                 sore throat
PH00004   0                       fever
PH00005   0                       cough
PH00006   0                       cough
          1     difficulty in breathing
PH00008   0                       fever
          1                 sore throat
PH00010   0                       fever
          1                       cough
PH00011   0                       cough
          1                 comorbidity
PH00012   0                       fever
          1                       cough
PH00013   0                       fever
PH00014   0                       fever
          1                       cough
PH00015   0                       cough
PH00016   0                       cough
          1                 sore throat
          2                       colds
PH00017   0                       cough
          1                       colds
PH00018   0                       fever
          1                    headache
          2                body malaise
PH00019   0                asymptomatic
PH00020   0                       cough
          1                body malaise
PH00022   0                       cough
          1                       colds
          2                   dysphagia
PH00023   0                       cough
          1                 sore throat
          2                    headache
PH00025   0                asymptomatic
PH00026   0                asymptomatic
PH00027   0                       cough
PH00028   0                       fever
          1                       cough
PH00029   0     difficulty of breathing
PH00030   0                     dyspnea
PH00031   0                 sore throat
PH00033   0                       fever
          1                       cough
          2                   dizziness
PH00099   0                       fever
          1                       cough
          2         shortness of breath
dtype: object

In [31]:
symptoms= pd.get_dummies(symptoms, prefix='symp').groupby(level=0).sum()
symptoms

,symp_ body malaise,symp_ colds,symp_ comorbidity,symp_ cough,symp_ difficulty in breathing,symp_ dizziness,symp_ dysphagia,symp_ headache,symp_ shortness of breath,symp_ sore throat,symp_asymptomatic,symp_cough,symp_difficulty of breathing,symp_dyspnea,symp_fever,symp_sore throat
phcaseno,,,,,,,,,,,,,,,,
PH00002,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
PH00004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
PH00005,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
PH00006,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
PH00008,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
PH00010,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
PH00011,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
PH00012,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
PH00013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
PH00014,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
PH00015,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
PH00016,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0
PH00017,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
PH00018,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
PH00019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
PH00020,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
PH00022,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0
PH00023,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0
PH00025,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
PH00026,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
PH00027,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
PH00028,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
PH00029,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
PH00030,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
PH00031,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
PH00033,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0
PH00099,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0

In [32]:
# join it back to the original 

clean_symptoms = data_clean.merge(symptoms, on=['phcaseno'], how='left', indicator=True)

In [33]:
clean_symptoms

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Epi_Link,Date of Onset of Symptoms,Date of Admission,Date of Lab Confirmation,...,symp_ headache,symp_ shortness of breath,symp_ sore throat,symp_asymptomatic,symp_cough,symp_difficulty of breathing,symp_dyspnea,symp_fever,symp_sore throat,_merge
0,PH00001,F,38,chinese,None,Yes (China); Wife of PH02,Wife of PH2,Tue Jan 21 00:00:00 EST 2020,Sat Jan 25 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,PH00002,M,44,chinese,None,Yes (China); Husband of PH1,Husband of PH1,Sat Jan 18 00:00:00 EST 2020,Sat Jan 25 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,both
2,PH00003,F,60,chinese,None,Yes (China),Traveled to Cebu and Bohol. Was already in Chi...,Tue Jan 21 00:00:00 EST 2020,Wed Jan 22 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,PH00004,M,48,filipino,Taguig City,Yes (Japan),NaN,Tue Mar 03 00:00:00 EST 2020,Fri Mar 06 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,both
4,PH00005,M,62,filipino,"Cainta, Rizal",Husband of PH06,Husband of PH6,Tue Feb 25 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3241,PH03242,F,65,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3242,PH03243,F,24,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3243,PH03244,M,48,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3244,PH03245,M,67,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3245,PH03246,F,15,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [34]:
clean_symptoms.columns

Index(['phcaseno', 'Sex', 'Age', 'Nationality', 'Residence in the Philippines',
       'History of Travel / Exposure', 'Epi_Link', 'Date of Onset of Symptoms',
       'Date of Admission', 'Date of Lab Confirmation',
       'Date of Announcement to the Public', 'Admission / Consultation',
       'Symptoms', 'Other disease', 'Status', 'Health Status',
       'Date of Final Status (recovered/expired)', 'Final Diagnosis',
       'Age Group', 'Location', 'Location 1', 'Location 2', 'Latitude',
       'Longitude', 'Residence Lat', 'Residence Long', 'symp_ body malaise',
       'symp_ colds', 'symp_ comorbidity', 'symp_ cough',
       'symp_ difficulty in breathing', 'symp_ dizziness', 'symp_ dysphagia',
       'symp_ headache', 'symp_ shortness of breath', 'symp_ sore throat',
       'symp_asymptomatic', 'symp_cough', 'symp_difficulty of breathing',
       'symp_dyspnea', 'symp_fever', 'symp_sore throat', '_merge'],
      dtype='object')

In [35]:
cols = ['symp_ body malaise',
       'symp_ colds', 'symp_ comorbidity', 'symp_ cough',
       'symp_ difficulty in breathing', 'symp_ dizziness', 'symp_ dysphagia',
       'symp_ headache', 'symp_ shortness of breath', 'symp_ sore throat',
       'symp_asymptomatic', 'symp_cough', 'symp_difficulty of breathing',
       'symp_dyspnea', 'symp_fever', 'symp_sore throat']

In [43]:
clean_symptoms[cols] = clean_symptoms[cols].replace({np.nan:0.0})

In [45]:
clean_symptoms

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Epi_Link,Date of Onset of Symptoms,Date of Admission,Date of Lab Confirmation,...,symp_ headache,symp_ shortness of breath,symp_ sore throat,symp_asymptomatic,symp_cough,symp_difficulty of breathing,symp_dyspnea,symp_fever,symp_sore throat,_merge
0,PH00001,F,38,chinese,None,Yes (China); Wife of PH02,Wife of PH2,Tue Jan 21 00:00:00 EST 2020,Sat Jan 25 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only
1,PH00002,M,44,chinese,None,Yes (China); Husband of PH1,Husband of PH1,Sat Jan 18 00:00:00 EST 2020,Sat Jan 25 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,both
2,PH00003,F,60,chinese,None,Yes (China),Traveled to Cebu and Bohol. Was already in Chi...,Tue Jan 21 00:00:00 EST 2020,Wed Jan 22 00:00:00 EST 2020,Thu Jan 30 00:00:00 EST 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only
3,PH00004,M,48,filipino,Taguig City,Yes (Japan),NaN,Tue Mar 03 00:00:00 EST 2020,Fri Mar 06 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,both
4,PH00005,M,62,filipino,"Cainta, Rizal",Husband of PH06,Husband of PH6,Tue Feb 25 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,Thu Mar 05 00:00:00 EST 2020,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3241,PH03242,F,65,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only
3242,PH03243,F,24,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only
3243,PH03244,M,48,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only
3244,PH03245,M,67,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only
3245,PH03246,F,15,filipino,For validation,0,NaN,NaN,NaN,Fri Apr 03 00:00:00 EDT 2020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only

In [113]:
import geopy

from geopy.geocoders import Nominatim

In [115]:
geolocator = Nominatim(user_agent="covid_19")

In [119]:
location = geolocator.reverse("14.59872, 120.9819909")

In [213]:
location

Location(SM Quiapo, Carlos Palanca Sr., Quiapo, Manila, Quiapo, Third District, Metro Manila, 1001, Philippines, (14.59869615, 120.98191084667977, 0.0))

In [ ]:
for elem in

In [164]:
# # Install a pip package in the current Jupyter kernel
# import sys
# !{sys.executable} -m pip install plotly_express

In [131]:
import plotly_express as px

In [134]:
# px.scatter_mapbox(data_clean, lat='Latitude', lon='Longitude', zoom=1000)

In [166]:
# # Install a pip package in the current Jupyter kernel
# import sys
# !{sys.executable} -m pip install geopandas

In [148]:
# %load_ext au totime
import pandas as pd

import geopandas as gpd
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

import matplotlib.pyplot as plt
import plotly_express as px
import tqdm
from tqdm import tqdm
from tqdm._tqdm_notebook import tqdm_notebook

In [190]:
data_clean['geom'] = data_clean['Latitude'].map(str) + ',' + data_clean['Longitude'].map(str)
# data_clean['geom'] = (str(data_clean['Latitude']) + ',' + str(data_clean['Longitude']))

In [191]:
data_clean.head()

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,Final Diagnosis,Age Group,Location,case_location,Location 2,Latitude,Longitude,Residence Lat,Residence Long,geom
0,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,NaN,31 - 40,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909,"14.61348,120.98095"
1,PH00002,M,44,Chinese,None,Yes (China); Husband of PH1,China,NaN,NaN,NaN,...,Severe Pneumonia,41 - 50,Manila City,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909,"14.61348,120.98095"
2,PH00003,F,60,Chinese,None,Yes (China),China,NaN,NaN,NaN,...,NaN,51 - 60,Manila City,Manila City,NaN,14.615867,120.980991,14.598727,120.9819909,"14.615867000000001,120.98099099999999"
3,PH00004,M,48,Filipino,Taguig City,Yes (Japan),Japan,NaN,NaN,NaN,...,"Asymptomatic, Negative Test Result",41 - 50,Taguig City,Taguig City,NaN,14.606904,121.020392,14.517274,121.0496133,"14.6069038,121.02039180000001"
4,PH00005,M,62,Filipino,"Cainta, Rizal",Husband of PH06,None,NaN,NaN,NaN,...,"Acute Respiratory Distress Syndrome, Severe pn...",61 - 70,"Cainta, Rizal",Cainta,Rizal,14.409635,121.037425,14.586506,121.1138255,"14.409634699999998,121.03742450000001"

In [196]:
# create a service provider locator this time pass timeout to be 10 minutes 
locator = Nominatim(user_agent='add_geom', timeout=30)
# rgeocode = RateLimiter(locator.reverse, min_delay_seconds=0.001)
rgeocode = RateLimiter(geolocator.reverse, min_delay_seconds=0.001)

In [197]:
rgeocode

In [192]:
# data_clean.geom[0]

In [209]:
# data_clean['patient_city'] = data_clean['geom'].apply(lambda a: a.city)

# create concatenated lat+lng column then reverse geocode each value
data_clean['geom'] = data_clean.apply(lambda row: '{},{}'.format(row['Latitude'], row['Longitude']), axis=1)

In [200]:
# tqdm.pandas()

# data_clean['patient_address'] = data_clean['geom'].progress_apply(rgeocode)

data_clean['geocode_data'] = ''
data_clean['city'] = ''
data_clean['country'] = ''

In [214]:
data_clean

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,case_location,Location 2,Latitude,Longitude,Residence Lat,Residence Long,geom,geocode_data,city,country
0,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909,"14.61348,120.98095",{},,
1,PH00002,M,44,Chinese,None,Yes (China); Husband of PH1,China,NaN,NaN,NaN,...,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909,"14.61348,120.98095",{},,
2,PH00003,F,60,Chinese,None,Yes (China),China,NaN,NaN,NaN,...,Manila City,NaN,14.615867,120.980991,14.598727,120.9819909,"14.615867000000001,120.98099099999999",{},,
3,PH00004,M,48,Filipino,Taguig City,Yes (Japan),Japan,NaN,NaN,NaN,...,Taguig City,NaN,14.606904,121.020392,14.517274,121.0496133,"14.6069038,121.02039180000001",{},,
4,PH00005,M,62,Filipino,"Cainta, Rizal",Husband of PH06,None,NaN,NaN,NaN,...,Cainta,Rizal,14.409635,121.037425,14.586506,121.1138255,"14.409634699999998,121.03742450000001",{},,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3241,PH03242,F,65,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3242,PH03243,F,24,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3243,PH03244,M,48,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3244,PH03245,M,67,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3245,PH03246,F,15,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,

In [204]:
import requests
def reverse_geocode(latlng):
    result = {}
    url = 'https://maps.googleapis.com/maps/api/geocode/json?latlng={}'
    request = url.format(latlng)
    data = requests.get(request).json()
    if len(data['results']) > 0:
        result = data['results'][0]
    return result

In [215]:
# data_clean['geocode_data'] = data_clean['geom'].map(reverse_geocode)
data_clean['geocode_data'] = geolocator.reverse(data_clean['geom'])

ValueError: Must be a coordinate pair or Point

In [212]:
data_clean

,phcaseno,Sex,Age,Nationality,Residence in the Philippines,History of Travel / Exposure,Travel History 1,Travel History 2,Travel History 3,Travel History 4,...,case_location,Location 2,Latitude,Longitude,Residence Lat,Residence Long,geom,geocode_data,city,country
0,PH00001,F,38,Chinese,None,Yes (China); Wife of PH02,China,NaN,NaN,NaN,...,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909,"14.61348,120.98095",{},,
1,PH00002,M,44,Chinese,None,Yes (China); Husband of PH1,China,NaN,NaN,NaN,...,Manila City,NaN,14.613480,120.980950,14.598727,120.9819909,"14.61348,120.98095",{},,
2,PH00003,F,60,Chinese,None,Yes (China),China,NaN,NaN,NaN,...,Manila City,NaN,14.615867,120.980991,14.598727,120.9819909,"14.615867000000001,120.98099099999999",{},,
3,PH00004,M,48,Filipino,Taguig City,Yes (Japan),Japan,NaN,NaN,NaN,...,Taguig City,NaN,14.606904,121.020392,14.517274,121.0496133,"14.6069038,121.02039180000001",{},,
4,PH00005,M,62,Filipino,"Cainta, Rizal",Husband of PH06,None,NaN,NaN,NaN,...,Cainta,Rizal,14.409635,121.037425,14.586506,121.1138255,"14.409634699999998,121.03742450000001",{},,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3241,PH03242,F,65,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3242,PH03243,F,24,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3243,PH03244,M,48,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3244,PH03245,M,67,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,
3245,PH03246,F,15,Filipino,For validation,0,For validation,NaN,NaN,NaN,...,For validation,NaN,14.615867,120.980991,14.615867,120.980991,"14.615867000000001,120.98099099999999",{},,

In [ ]:
df[['V','allele']] = df['V'].str.split('-',expand=True)

Important Links: 
- https://colab.research.google.com/github/shakasom/geocoding/blob/master/ReverseGeocoding.ipynb 
- https://stackoverflow.com/questions/37333299/splitting-a-column-by-delimiter-pandas-python
- https://chrisalbon.com/python/data_wrangling/geocoding_and_reverse_geocoding/
- https://stackoverflow.com/questions/34962104/pandas-how-can-i-use-the-apply-function-for-a-single-column
- https://geopy.readthedocs.io/en/1.10.0/
- https://geoffboeing.com/2014/08/reverse-geocode-a-set-of-lat-long-coordinates-to-city-country/
- https://github.com/gboeing/2014-summer-travels/blob/master/reverse-geocode-latlong.ipynb
- https://towardsdatascience.com/reverse-geocoding-in-python-a915acf29eb6
- https://geopy.readthedocs.io/en/stable/#installation
- https://geopandas.org/geocoding.html
- https://towardsdatascience.com/geocode-with-python-161ec1e62b89

- https://drive.google.com/drive/u/2/folders/10VkiUA8x7TS2jkibhSZK1gmWxFM-EoZP 
- https://docs.google.com/spreadsheets/d/16g_PUxKYMC0XjeEKF6FPUBq2-pFgmTkHoj5lbVrGLhE/edit?fbclid=IwAR2YAvYMTGDR0r_m2tQRV20pjniUufhL10w57q02v1DN0uxWr_HuTRrZwD8#gid=0
- https://docs.google.com/spreadsheets/d/1QxIMnM-Vn7ea3hNPJYatrP9Dd2kicVkBRBFZZW_mHq8/edit#gid=1748029833
- https://drive.google.com/drive/u/2/folders/1zf3p0ORcRn2ngabcy2aFOnOvCt8DiOkR